### ISSUE TITLE
Migrate Member Info

### ISSUE THREAD

**Issue by mattwalo32** [hack4impact-uiuc/memberdb-tool#17]
Migrate member info from previous semesters to the atlas DB.
[Previous Semester](https://docs.google.com/spreadsheets/u/1/d/1gznjf7LUG0nA45XprY_mE_z3fTsVx16cgWXl881CO5w/edit#gid=0)

**Comment by Qrtn** [comment]
For easier parsing, would recommending exporting spreadsheet as CSV, and it might be slightly easier to PUT the endpoint in a Python script rather than directly inserting into DB.
