### ISSUE TITLE
Add attribute editing to Profile page

### ISSUE THREAD

**Issue by mattwalo32** [hack4impact-uiuc/memberdb-tool#32]
Users are currently able to edit fields about a member's info on the frontend (provided they have proper permissions). Add a button to the Profile page that makes a PUT request to update the member's data after changes are made on the frontend.

For components, use [H4I Bridge](https://bridge-ui.now.sh/components/buttons)

Use the PUT /members/:memberID endpoint

**Comment by Qrtn** [comment]
Was wondering if it were possible to implement @alicesf2's suggestion to condense the input fields to reduce vertical scrolling? Could be alongside this or in another issue.

**Comment by mattwalo32** [comment]
I made a new issue for that #38
