### ISSUE TITLE
Add notes table to frontend

### ISSUE THREAD

**Issue by mattwalo32** [hack4impact-uiuc/memberdb-tool#35]
Add a frontend route /notes. This should display an ag-grid table of all notes a user can view (handled by the backend).

We should put a "view notes" button on the profile page that redirects to /notes?memberID=. The ag-grid should filter to notes where referencedMembers includes memberID.

When a note is clicked on, redirect the member to /notes/:noteID. This page will be handled in another issue.

Add a button on the /notes page to create a new note. Look into using [draft.js](https://draftjs.org) or [markdown draft.js](https://www.npmjs.com/package/markdown-draft-js
).

**Comment by Qrtn** [comment]
I agree with making a new page just for notes. I think we should show all notes in a table format. This table would include a bunch of columns:

- Title
- Applies to which members
- Last edited
- ...and all the other metadata

This table would show *all* notes for which the current logged-in user has access to. Similar to the member profile page, editing a note would involve clicking a row in the table, which would bring the user to the note editing page.

The "view notes" button on a member's profile page makes sense. I think we could implement that by having it link to the table view, but with query params filtering for that member's id.
